//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginISP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product2
    {
        public int IdProduct2 { get; set; }
        public string Name2 { get; set; }
        public Nullable<int> Quantity2 { get; set; }
        public Nullable<int> IdCategory2 { get; set; }
        public string Image2 { get; set; }
    
        public virtual Category2 Category2 { get; set; }
    }
}
